package com.aw.util;

/**
 * A generator of tenant singleton instances of a particular type
 *
 *
 *
 * @param <T> The type of singleton generated by this factory
 */
public interface TenantSingletonFactory<T> {

	/**
	 * @return A new tenant singleton of the given type
	 */
	public T newInstance();

}
