package com.aw.incident;

/**
 * Used to incidate how something was created, either by the system or by a user
 *
 *
 *
 */
public enum CreationType {

	/**
	 * Incident was generated by the system
	 */
	AUTOMATIC,

	/**
	 * Incident was created by a user
	 */
	MANUAL

}
